package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("ABEF1000 - Vendor Recommendation")
internal class ABEF1000VendorRecommendation {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == 14 // Vendor Recommendation
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/
// execute child rules

/*end00rule*/

  }
}
