package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("PolicyCenter")
internal class PolicyCenter {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == gw.plugin.integration.InitializableClientSystemTransport.DestinationID("PCPolicySystemTransport")
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
